### ISSUE TITLE
peer to peer

### ISSUE THREAD

**Issue by marilirulita** [joseheco/Webpack-TODO-List#4]
Very nice project, congratulations.
It works very well and the style is very cool.

I just have one suggestions for improve it:
- It would be good if the value in the input element for add new task change to empty after your add the new task.

keep doing the good job!

**Comment by lisandroseia** [comment]
Hi, your project is very good, and the logic is perfect.
There is only one thing that I think you could do to improve it:
When you use a function to export the array, you could use export and it will allow you to export it, if you have problems later, you could use concat instead of push.
I hope this helps you, good look with your project
